CREATE TABLE Sensors
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL UNIQUE
);

CREATE TABLE Measurements
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value      REAL NOT NULL CHECK (value >= -100 AND value <= 100),
    raining    BOOLEAN,
    created_at TIMESTAMP,
    sensor_id  int REFERENCES Sensors (id) ON DELETE CASCADE
);
